// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT36FtvrU53SKXhwHsIpz3nQeFaFpKH0c',
    appId: '1:638701611026:web:195bf37eb4e885907a50cb',
    messagingSenderId: '638701611026',
    projectId: 'edunudge-ceed4',
    authDomain: 'edunudge-ceed4.firebaseapp.com',
    storageBucket: 'edunudge-ceed4.firebasestorage.app',
    measurementId: 'G-1KD3XGJL0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8pPA1vowZw8_c5hMxXY7HMic3iNvL668',
    appId: '1:638701611026:android:bf4d06d9bacdbc567a50cb',
    messagingSenderId: '638701611026',
    projectId: 'edunudge-ceed4',
    storageBucket: 'edunudge-ceed4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdSE0hWWlZyGRL0e50FZlA1BwYjLci7eY',
    appId: '1:638701611026:ios:ca7e3651869f26337a50cb',
    messagingSenderId: '638701611026',
    projectId: 'edunudge-ceed4',
    storageBucket: 'edunudge-ceed4.firebasestorage.app',
    iosBundleId: 'com.example.edunudge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdSE0hWWlZyGRL0e50FZlA1BwYjLci7eY',
    appId: '1:638701611026:ios:ca7e3651869f26337a50cb',
    messagingSenderId: '638701611026',
    projectId: 'edunudge-ceed4',
    storageBucket: 'edunudge-ceed4.firebasestorage.app',
    iosBundleId: 'com.example.edunudge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT36FtvrU53SKXhwHsIpz3nQeFaFpKH0c',
    appId: '1:638701611026:web:92e7b73a504d59c77a50cb',
    messagingSenderId: '638701611026',
    projectId: 'edunudge-ceed4',
    authDomain: 'edunudge-ceed4.firebaseapp.com',
    storageBucket: 'edunudge-ceed4.firebasestorage.app',
    measurementId: 'G-81L2GLWLGB',
  );
}
